"""Database Models for Visualization and Dashboard Management

This module contains SQLAlchemy models for storing visualization metadata,
dashboard configurations, insight narratives, and user preferences.
"""

from sqlalchemy import (
    Column, Integer, String, Text, DateTime, Boolean, Float, 
    JSON, ForeignKey, Index, UniqueConstraint, CheckConstraint,
    Enum, LargeBinary, Table
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, backref
from sqlalchemy.dialects.postgresql import UUID, JSONB, ARRAY
from sqlalchemy.sql import func
from datetime import datetime
from typing import Dict, List, Optional, Any
import uuid
import enum

# Create base class
Base = declarative_base()


# Enums for model fields
class ChartType(enum.Enum):
    """Chart types supported by the visualization system."""
    BAR = "bar"
    LINE = "line"
    SCATTER = "scatter"
    PIE = "pie"
    HISTOGRAM = "histogram"
    BOX = "box"
    HEATMAP = "heatmap"
    AREA = "area"
    TREEMAP = "treemap"
    TABLE = "table"
    GAUGE = "gauge"
    FUNNEL = "funnel"


class DashboardType(enum.Enum):
    """Dashboard types for different use cases."""
    EXECUTIVE = "executive"
    OPERATIONAL = "operational"
    ANALYTICAL = "analytical"
    KPI = "kpi"
    CUSTOM = "custom"


class InsightType(enum.Enum):
    """Types of insights generated by AI."""
    TREND = "trend"
    ANOMALY = "anomaly"
    CORRELATION = "correlation"
    DISTRIBUTION = "distribution"
    COMPARISON = "comparison"
    FORECAST = "forecast"
    SUMMARY = "summary"
    RECOMMENDATION = "recommendation"


class VisualizationStatus(enum.Enum):
    """Status of visualization generation."""
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    CACHED = "cached"


class ShareLevel(enum.Enum):
    """Sharing levels for dashboards and visualizations."""
    PRIVATE = "private"
    TEAM = "team"
    ORGANIZATION = "organization"
    PUBLIC = "public"


# Association table for many-to-many relationships
dashboard_charts = Table(
    'dashboard_charts',
    Base.metadata,
    Column('dashboard_id', UUID(as_uuid=True), ForeignKey('dashboards.id'), primary_key=True),
    Column('chart_id', UUID(as_uuid=True), ForeignKey('charts.id'), primary_key=True),
    Column('position_x', Integer, default=0),
    Column('position_y', Integer, default=0),
    Column('width', Integer, default=400),
    Column('height', Integer, default=300),
    Column('created_at', DateTime(timezone=True), server_default=func.now())
)

user_dashboard_favorites = Table(
    'user_dashboard_favorites',
    Base.metadata,
    Column('user_id', String(255), primary_key=True),
    Column('dashboard_id', UUID(as_uuid=True), ForeignKey('dashboards.id'), primary_key=True),
    Column('created_at', DateTime(timezone=True), server_default=func.now())
)


class User(Base):
    """User model for authentication and preferences."""
    __tablename__ = 'users'
    
    id = Column(String(255), primary_key=True)
    email = Column(String(255), unique=True, nullable=False, index=True)
    name = Column(String(255), nullable=False)
    role = Column(String(50), default='analyst')
    preferences = Column(JSONB, default=dict)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    last_login = Column(DateTime(timezone=True))
    is_active = Column(Boolean, default=True)
    
    # Relationships
    charts = relationship("Chart", back_populates="creator", cascade="all, delete-orphan")
    dashboards = relationship("Dashboard", back_populates="creator", cascade="all, delete-orphan")
    insights = relationship("InsightNarrative", back_populates="creator", cascade="all, delete-orphan")
    favorite_dashboards = relationship(
        "Dashboard", 
        secondary=user_dashboard_favorites, 
        back_populates="favorited_by"
    )
    
    # Indexes
    __table_args__ = (
        Index('idx_users_email', 'email'),
        Index('idx_users_active', 'is_active'),
    )
    
    def __repr__(self):
        return f"<User(id='{self.id}', email='{self.email}')>"


class DataSource(Base):
    """Data source configuration for charts and dashboards."""
    __tablename__ = 'data_sources'
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String(255), nullable=False)
    source_type = Column(String(50), nullable=False)  # 'bigquery', 'csv', 'api', etc.
    connection_params = Column(JSONB, nullable=False)
    schema_info = Column(JSONB, default=dict)
    refresh_schedule = Column(String(100))  # Cron expression
    last_refresh = Column(DateTime(timezone=True))
    cache_duration = Column(Integer, default=3600)  # seconds
    is_active = Column(Boolean, default=True)
    created_by = Column(String(255), ForeignKey('users.id'))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Relationships
    charts = relationship("Chart", back_populates="data_source")
    
    # Indexes
    __table_args__ = (
        Index('idx_data_sources_type', 'source_type'),
        Index('idx_data_sources_active', 'is_active'),
    )
    
    def __repr__(self):
        return f"<DataSource(id='{self.id}', name='{self.name}', type='{self.source_type}')>"


class Chart(Base):
    """Individual chart/visualization configuration."""
    __tablename__ = 'charts'
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    title = Column(String(255), nullable=False)
    description = Column(Text)
    chart_type = Column(Enum(ChartType), nullable=False)
    
    # Chart configuration
    config = Column(JSONB, nullable=False)  # Plotly/chart-specific config
    data_query = Column(Text)  # SQL query or data retrieval logic
    data_source_id = Column(UUID(as_uuid=True), ForeignKey('data_sources.id'))
    
    # Styling and layout
    styling = Column(JSONB, default=dict)
    layout_config = Column(JSONB, default=dict)
    color_scheme = Column(String(50), default='default')
    
    # Generation metadata
    generated_from_query = Column(Text)  # Original natural language query
    ai_confidence_score = Column(Float)  # Confidence in AI-generated chart
    generation_metadata = Column(JSONB, default=dict)
    
    # Status and caching
    status = Column(Enum(VisualizationStatus), default=VisualizationStatus.PENDING)
    cache_key = Column(String(255), index=True)
    last_rendered = Column(DateTime(timezone=True))
    render_time_ms = Column(Integer)  # Rendering performance metric
    
    # Sharing and permissions
    share_level = Column(Enum(ShareLevel), default=ShareLevel.PRIVATE)
    shared_with = Column(ARRAY(String), default=list)  # User IDs with access
    
    # Audit fields
    created_by = Column(String(255), ForeignKey('users.id'), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    version = Column(Integer, default=1)
    
    # Usage statistics
    view_count = Column(Integer, default=0)
    last_viewed = Column(DateTime(timezone=True))
    export_count = Column(Integer, default=0)
    
    # Relationships
    creator = relationship("User", back_populates="charts")
    data_source = relationship("DataSource", back_populates="charts")
    dashboards = relationship("Dashboard", secondary=dashboard_charts, back_populates="charts")
    versions = relationship("ChartVersion", back_populates="chart", cascade="all, delete-orphan")
    
    # Indexes
    __table_args__ = (
        Index('idx_charts_creator', 'created_by'),
        Index('idx_charts_type', 'chart_type'),
        Index('idx_charts_status', 'status'),
        Index('idx_charts_share_level', 'share_level'),
        Index('idx_charts_cache_key', 'cache_key'),
        Index('idx_charts_created_at', 'created_at'),
    )
    
    def __repr__(self):
        return f"<Chart(id='{self.id}', title='{self.title}', type='{self.chart_type}')>"


class ChartVersion(Base):
    """Version history for charts."""
    __tablename__ = 'chart_versions'
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    chart_id = Column(UUID(as_uuid=True), ForeignKey('charts.id'), nullable=False)
    version_number = Column(Integer, nullable=False)
    
    # Snapshot of chart configuration
    config_snapshot = Column(JSONB, nullable=False)
    styling_snapshot = Column(JSONB, default=dict)
    query_snapshot = Column(Text)
    
    # Version metadata
    change_summary = Column(Text)
    changed_by = Column(String(255), ForeignKey('users.id'))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    chart = relationship("Chart", back_populates="versions")
    
    # Constraints
    __table_args__ = (
        UniqueConstraint('chart_id', 'version_number', name='uq_chart_version'),
        Index('idx_chart_versions_chart', 'chart_id'),
    )
    
    def __repr__(self):
        return f"<ChartVersion(chart_id='{self.chart_id}', version={self.version_number})>"


class Dashboard(Base):
    """Dashboard containing multiple charts and configurations."""
    __tablename__ = 'dashboards'
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    title = Column(String(255), nullable=False)
    description = Column(Text)
    dashboard_type = Column(Enum(DashboardType), default=DashboardType.CUSTOM)
    
    # Dashboard configuration
    layout_config = Column(JSONB, nullable=False)  # Grid layout, dimensions, etc.
    theme_config = Column(JSONB, default=dict)  # Colors, fonts, styling
    filter_config = Column(JSONB, default=dict)  # Global filters
    
    # Generated dashboard metadata
    generated_from_query = Column(Text)  # Original query that generated this dashboard
    template_id = Column(String(100))  # Template used for generation
    ai_confidence_score = Column(Float)
    generation_metadata = Column(JSONB, default=dict)
    
    # Looker Studio integration
    looker_dashboard_id = Column(String(255), unique=True)
    looker_embed_url = Column(Text)
    looker_edit_url = Column(Text)
    
    # Status and performance
    status = Column(Enum(VisualizationStatus), default=VisualizationStatus.PENDING)
    last_refreshed = Column(DateTime(timezone=True))
    refresh_duration_ms = Column(Integer)
    
    # Sharing and permissions
    share_level = Column(Enum(ShareLevel), default=ShareLevel.PRIVATE)
    shared_with = Column(ARRAY(String), default=list)
    embed_token = Column(String(255), unique=True)  # For public embedding
    
    # Audit fields
    created_by = Column(String(255), ForeignKey('users.id'), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Usage statistics
    view_count = Column(Integer, default=0)
    last_viewed = Column(DateTime(timezone=True))
    favorite_count = Column(Integer, default=0)
    
    # Relationships
    creator = relationship("User", back_populates="dashboards")
    charts = relationship("Chart", secondary=dashboard_charts, back_populates="dashboards")
    favorited_by = relationship("User", secondary=user_dashboard_favorites, back_populates="favorite_dashboards")
    
    # Indexes
    __table_args__ = (
        Index('idx_dashboards_creator', 'created_by'),
        Index('idx_dashboards_type', 'dashboard_type'),
        Index('idx_dashboards_status', 'status'),
        Index('idx_dashboards_share_level', 'share_level'),
        Index('idx_dashboards_created_at', 'created_at'),
        Index('idx_dashboards_looker_id', 'looker_dashboard_id'),
    )
    
    def __repr__(self):
        return f"<Dashboard(id='{self.id}', title='{self.title}', type='{self.dashboard_type}')>"


class InsightNarrative(Base):
    """AI-generated insights and narratives from data analysis."""
    __tablename__ = 'insight_narratives'
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    title = Column(String(255), nullable=False)
    
    # Narrative content
    executive_summary = Column(Text, nullable=False)
    detailed_narrative = Column(Text, nullable=False)
    key_insights = Column(JSONB, nullable=False)  # Array of insight objects
    action_items = Column(ARRAY(Text), default=list)
    
    # Source data and query
    source_query = Column(Text)  # Original query or data source
    query_metadata = Column(JSONB, default=dict)
    data_fingerprint = Column(String(64))  # Hash of source data for caching
    
    # AI generation metadata
    model_used = Column(String(100))  # e.g., 'gemini-1.5-pro'
    generation_config = Column(JSONB, default=dict)
    confidence_scores = Column(JSONB, default=dict)  # Confidence by insight type
    generation_time_ms = Column(Integer)
    
    # Visualization recommendations
    viz_recommendations = Column(JSONB, default=list)  # Recommended charts/visualizations
    
    # Status and caching
    status = Column(Enum(VisualizationStatus), default=VisualizationStatus.PENDING)
    cache_key = Column(String(255), index=True)
    
    # Sharing
    share_level = Column(Enum(ShareLevel), default=ShareLevel.PRIVATE)
    shared_with = Column(ARRAY(String), default=list)
    
    # Audit fields
    created_by = Column(String(255), ForeignKey('users.id'), nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Usage statistics
    view_count = Column(Integer, default=0)
    last_viewed = Column(DateTime(timezone=True))
    
    # Relationships
    creator = relationship("User", back_populates="insights")
    
    # Indexes
    __table_args__ = (
        Index('idx_insights_creator', 'created_by'),
        Index('idx_insights_status', 'status'),
        Index('idx_insights_fingerprint', 'data_fingerprint'),
        Index('idx_insights_cache_key', 'cache_key'),
        Index('idx_insights_created_at', 'created_at'),
    )
    
    def __repr__(self):
        return f"<InsightNarrative(id='{self.id}', title='{self.title[:50]}...')>"


class QueryCache(Base):
    """Cache for expensive query results and computations."""
    __tablename__ = 'query_cache'
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    cache_key = Column(String(255), unique=True, nullable=False, index=True)
    query_hash = Column(String(64), nullable=False, index=True)  # Hash of SQL query
    
    # Cached data
    result_data = Column(LargeBinary)  # Pickled/compressed result data
    result_metadata = Column(JSONB, default=dict)  # Schema, row count, etc.
    
    # Cache configuration
    ttl_seconds = Column(Integer, default=3600)
    cache_level = Column(String(50), default='session')  # temporary, session, persistent
    
    # Performance metrics
    original_query_time_ms = Column(Integer)
    data_size_bytes = Column(Integer)
    compression_ratio = Column(Float)
    
    # Usage tracking
    hit_count = Column(Integer, default=0)
    last_accessed = Column(DateTime(timezone=True))
    
    # Audit fields
    created_by = Column(String(255), ForeignKey('users.id'))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    expires_at = Column(DateTime(timezone=True), nullable=False)
    
    # Indexes
    __table_args__ = (
        Index('idx_query_cache_key', 'cache_key'),
        Index('idx_query_cache_hash', 'query_hash'),
        Index('idx_query_cache_expires', 'expires_at'),
        Index('idx_query_cache_created', 'created_at'),
    )
    
    def __repr__(self):
        return f"<QueryCache(cache_key='{self.cache_key}', expires_at='{self.expires_at}')>"


class UserPreferences(Base):
    """User-specific preferences for visualizations and dashboards."""
    __tablename__ = 'user_preferences'
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(String(255), ForeignKey('users.id'), nullable=False)
    
    # Visualization preferences
    default_chart_type = Column(Enum(ChartType), default=ChartType.BAR)
    preferred_color_scheme = Column(String(50), default='default')
    default_theme = Column(String(50), default='light')
    
    # Dashboard preferences
    default_dashboard_layout = Column(JSONB, default=dict)
    favorite_chart_types = Column(ARRAY(String), default=list)
    
    # AI and narrative preferences
    narrative_style = Column(String(50), default='executive')  # executive, technical, casual
    insight_confidence_threshold = Column(Float, default=0.7)
    auto_generate_insights = Column(Boolean, default=True)
    
    # Notification preferences
    notify_on_dashboard_share = Column(Boolean, default=True)
    notify_on_insight_generation = Column(Boolean, default=False)
    email_digest_frequency = Column(String(20), default='weekly')  # daily, weekly, monthly
    
    # Performance preferences
    enable_caching = Column(Boolean, default=True)
    cache_preference = Column(String(20), default='balanced')  # aggressive, balanced, minimal
    
    # Custom settings
    custom_settings = Column(JSONB, default=dict)
    
    # Audit fields
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Constraints
    __table_args__ = (
        UniqueConstraint('user_id', name='uq_user_preferences'),
        Index('idx_user_preferences_user', 'user_id'),
    )
    
    def __repr__(self):
        return f"<UserPreferences(user_id='{self.user_id}')>"


class SystemMetrics(Base):
    """System performance and usage metrics."""
    __tablename__ = 'system_metrics'
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    metric_name = Column(String(100), nullable=False)
    metric_value = Column(Float, nullable=False)
    metric_unit = Column(String(20))  # ms, bytes, count, percentage
    
    # Metric context
    component = Column(String(50))  # visualization, dashboard, insights, cache
    operation = Column(String(50))  # generation, query, render, cache_hit
    
    # Metadata
    metadata = Column(JSONB, default=dict)
    
    # Timestamp
    recorded_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Indexes
    __table_args__ = (
        Index('idx_system_metrics_name', 'metric_name'),
        Index('idx_system_metrics_component', 'component'),
        Index('idx_system_metrics_recorded', 'recorded_at'),
        Index('idx_system_metrics_name_component', 'metric_name', 'component'),
    )
    
    def __repr__(self):
        return f"<SystemMetrics(name='{self.metric_name}', value={self.metric_value})>"


class AuditLog(Base):
    """Audit log for tracking user actions and system events."""
    __tablename__ = 'audit_logs'
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    
    # Event details
    event_type = Column(String(50), nullable=False)  # CREATE, UPDATE, DELETE, VIEW, SHARE
    resource_type = Column(String(50), nullable=False)  # chart, dashboard, insight
    resource_id = Column(String(255), nullable=False)
    
    # User and session
    user_id = Column(String(255), ForeignKey('users.id'))
    session_id = Column(String(255))
    ip_address = Column(String(45))  # IPv6 compatible
    user_agent = Column(Text)
    
    # Event data
    event_data = Column(JSONB, default=dict)  # Additional event-specific data
    old_values = Column(JSONB, default=dict)  # For UPDATE events
    new_values = Column(JSONB, default=dict)  # For UPDATE events
    
    # Result
    success = Column(Boolean, default=True)
    error_message = Column(Text)
    
    # Timestamp
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Indexes
    __table_args__ = (
        Index('idx_audit_logs_user', 'user_id'),
        Index('idx_audit_logs_resource', 'resource_type', 'resource_id'),
        Index('idx_audit_logs_event', 'event_type'),
        Index('idx_audit_logs_created', 'created_at'),
        Index('idx_audit_logs_session', 'session_id'),
    )
    
    def __repr__(self):
        return f"<AuditLog(event='{self.event_type}', resource='{self.resource_type}:{self.resource_id}')>"


# Database utility functions
def create_tables(engine):
    """Create all tables in the database.
    
    Args:
        engine: SQLAlchemy engine instance
    """
    Base.metadata.create_all(bind=engine)


def drop_tables(engine):
    """Drop all tables from the database.
    
    Args:
        engine: SQLAlchemy engine instance
    """
    Base.metadata.drop_all(bind=engine)


# Example usage and model relationships demo
if __name__ == "__main__":
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker
    
    # Example: Create in-memory SQLite database for testing
    engine = create_engine("sqlite:///:memory:", echo=True)
    
    # Create all tables
    create_tables(engine)
    
    # Create session
    Session = sessionmaker(bind=engine)
    session = Session()
    
    try:
        # Create a test user
        user = User(
            id="test_user_123",
            email="analyst@example.com",
            name="Test Analyst",
            preferences={
                "theme": "dark",
                "default_chart": "bar"
            }
        )
        session.add(user)
        
        # Create a data source
        data_source = DataSource(
            name="Sales Database",
            source_type="bigquery",
            connection_params={
                "project_id": "my-project",
                "dataset": "sales"
            },
            created_by=user.id
        )
        session.add(data_source)
        
        # Create a chart
        chart = Chart(
            title="Monthly Revenue Trend",
            chart_type=ChartType.LINE,
            config={
                "x_axis": "month",
                "y_axis": "revenue",
                "color": "blue"
            },
            data_query="SELECT month, SUM(revenue) as revenue FROM sales GROUP BY month",
            data_source=data_source,
            created_by=user.id,
            ai_confidence_score=0.85
        )
        session.add(chart)
        
        # Create a dashboard
        dashboard = Dashboard(
            title="Sales Overview Dashboard",
            dashboard_type=DashboardType.EXECUTIVE,
            layout_config={
                "width": 1200,
                "height": 800,
                "grid_size": 20
            },
            created_by=user.id
        )
        session.add(dashboard)
        
        # Create user preferences
        preferences = UserPreferences(
            user_id=user.id,
            default_chart_type=ChartType.BAR,
            preferred_color_scheme="material",
            narrative_style="executive"
        )
        session.add(preferences)
        
        # Commit all changes
        session.commit()
        
        # Query examples
        print(f"Created user: {user}")
        print(f"Created chart: {chart}")
        print(f"Created dashboard: {dashboard}")
        
        # Demonstrate relationships
        user_charts = session.query(Chart).filter(Chart.created_by == user.id).all()
        print(f"User has {len(user_charts)} charts")
        
        print("Database models test completed successfully!")
        
    except Exception as e:
        print(f"Database test failed: {e}")
        session.rollback()
    finally:
        session.close()