"""BigQuery Query Validation and Safe Execution Service

This module provides comprehensive validation and safe execution of SQL queries
generated by the conversational system, including dry-run validation, security
checks, and performance analysis.
"""

import json
import logging
import re
from typing import Dict, List, Optional, Tuple, Any, Union
from dataclasses import dataclass
from datetime import datetime, timedelta
from enum import Enum

from google.cloud import bigquery
from google.cloud.exceptions import GoogleCloudError
import sqlparse
from sqlparse import sql, tokens

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class QueryRiskLevel(Enum):
    """Risk levels for SQL queries."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ValidationStatus(Enum):
    """Query validation status."""
    VALID = "valid"
    WARNING = "warning"
    BLOCKED = "blocked"
    ERROR = "error"


@dataclass
class QueryValidationResult:
    """Result of query validation."""
    status: ValidationStatus
    risk_level: QueryRiskLevel
    is_safe: bool
    estimated_cost: Optional[float]
    estimated_runtime: Optional[float]
    bytes_processed: Optional[int]
    warnings: List[str]
    errors: List[str]
    recommendations: List[str]
    metadata: Dict[str, Any]


@dataclass
class QueryExecutionResult:
    """Result of query execution."""
    success: bool
    query_job_id: str
    rows_returned: int
    bytes_processed: int
    execution_time: float
    cost_estimate: float
    results: Optional[List[Dict[str, Any]]]
    error_message: Optional[str]
    metadata: Dict[str, Any]


class BigQueryValidationService:
    """Service for validating and safely executing BigQuery queries."""
    
    def __init__(
        self,
        project_id: str,
        location: str = "US",
        max_cost_threshold: float = 10.0,  # USD
        max_bytes_threshold: int = 1024 * 1024 * 1024 * 10,  # 10GB
        max_execution_time: int = 300  # 5 minutes
    ):
        """Initialize the validation service.
        
        Args:
            project_id: GCP project ID
            location: BigQuery location
            max_cost_threshold: Maximum allowed query cost in USD
            max_bytes_threshold: Maximum bytes processed threshold
            max_execution_time: Maximum execution time in seconds
        """
        self.project_id = project_id
        self.location = location
        self.max_cost_threshold = max_cost_threshold
        self.max_bytes_threshold = max_bytes_threshold
        self.max_execution_time = max_execution_time
        
        # Initialize BigQuery client
        self.client = bigquery.Client(project=project_id, location=location)
        
        # Pricing information (USD per TB processed)
        self.bigquery_pricing = {
            "on_demand": 5.0,  # $5 per TB
            "flat_rate": 0.0   # Flat rate customers
        }
        
        # Define dangerous patterns and keywords
        self._load_security_rules()
    
    def _load_security_rules(self) -> None:
        """Load security rules and patterns."""
        # Dangerous SQL keywords (not allowed)
        self.dangerous_keywords = {
            'DELETE', 'DROP', 'TRUNCATE', 'INSERT', 'UPDATE', 
            'CREATE', 'ALTER', 'GRANT', 'REVOKE', 'EXEC',
            'EXECUTE', 'CALL', 'MERGE'
        }
        
        # Warning keywords (require attention)
        self.warning_keywords = {
            'UNION', 'CROSS JOIN', 'CARTESIAN', 'UNNEST'
        }
        
        # Expensive operations
        self.expensive_patterns = [
            r'SELECT\s+\*\s+FROM.*WHERE.*NOT IN.*SELECT',  # NOT IN subquery
            r'SELECT.*FROM.*WHERE.*LIKE\s+[\'"]%.*%[\'"]',  # Leading wildcard LIKE
            r'SELECT.*FROM.*WHERE.*REGEXP_CONTAINS',        # Regex operations
            r'SELECT.*FROM.*WHERE.*NOT\s+EXISTS',           # NOT EXISTS
        ]
        
        # Required patterns for safety
        self.required_patterns = {
            'limit_clause': r'\bLIMIT\s+\d+\b',
            'where_clause': r'\bWHERE\b',
        }
    
    def validate_query(self, sql_query: str, context: Optional[Dict[str, Any]] = None) -> QueryValidationResult:
        """Comprehensive query validation.
        
        Args:
            sql_query: SQL query to validate
            context: Additional context for validation
            
        Returns:
            Validation result with safety assessment
        """
        try:
            warnings = []
            errors = []
            recommendations = []
            
            # Parse SQL
            parsed = sqlparse.parse(sql_query)[0]
            
            # Security validation
            security_result = self._validate_security(sql_query, parsed)
            warnings.extend(security_result.get('warnings', []))
            errors.extend(security_result.get('errors', []))
            
            # Performance validation
            performance_result = self._validate_performance(sql_query, parsed)
            warnings.extend(performance_result.get('warnings', []))
            recommendations.extend(performance_result.get('recommendations', []))
            
            # BigQuery dry run
            dry_run_result = self._perform_dry_run(sql_query)
            
            # Calculate risk level
            risk_level = self._calculate_risk_level(
                security_result, performance_result, dry_run_result
            )
            
            # Determine validation status
            if errors:
                status = ValidationStatus.BLOCKED
                is_safe = False
            elif risk_level == QueryRiskLevel.CRITICAL:
                status = ValidationStatus.BLOCKED
                is_safe = False
            elif warnings or risk_level in [QueryRiskLevel.HIGH, QueryRiskLevel.MEDIUM]:
                status = ValidationStatus.WARNING
                is_safe = True  # Can execute with warnings
            else:
                status = ValidationStatus.VALID
                is_safe = True
            
            # Build result
            result = QueryValidationResult(
                status=status,
                risk_level=risk_level,
                is_safe=is_safe,
                estimated_cost=dry_run_result.get('estimated_cost'),
                estimated_runtime=dry_run_result.get('estimated_runtime'),
                bytes_processed=dry_run_result.get('bytes_processed'),
                warnings=warnings,
                errors=errors,
                recommendations=recommendations,
                metadata={
                    'query_length': len(sql_query),
                    'validation_time': datetime.now().isoformat(),
                    'context': context or {}
                }
            )
            
            logger.info(f"Query validation completed: {status.value}, risk: {risk_level.value}")
            return result
            
        except Exception as e:
            logger.error(f"Query validation failed: {str(e)}")
            return QueryValidationResult(
                status=ValidationStatus.ERROR,
                risk_level=QueryRiskLevel.CRITICAL,
                is_safe=False,
                estimated_cost=None,
                estimated_runtime=None,
                bytes_processed=None,
                warnings=[],
                errors=[f"Validation error: {str(e)}"],
                recommendations=[],
                metadata={'error': str(e)}
            )
    
    def execute_query_safely(
        self, 
        sql_query: str, 
        validation_result: Optional[QueryValidationResult] = None,
        max_results: int = 1000
    ) -> QueryExecutionResult:
        """Execute query with safety checks.
        
        Args:
            sql_query: SQL query to execute
            validation_result: Pre-computed validation result
            max_results: Maximum number of results to return
            
        Returns:
            Query execution result
        """
        try:
            # Validate if not already done
            if validation_result is None:
                validation_result = self.validate_query(sql_query)
            
            # Check if query is safe to execute
            if not validation_result.is_safe:
                return QueryExecutionResult(
                    success=False,
                    query_job_id="",
                    rows_returned=0,
                    bytes_processed=0,
                    execution_time=0.0,
                    cost_estimate=0.0,
                    results=None,
                    error_message="Query blocked due to safety concerns",
                    metadata={
                        'validation_status': validation_result.status.value,
                        'risk_level': validation_result.risk_level.value,
                        'errors': validation_result.errors
                    }
                )
            
            # Add LIMIT clause if not present
            limited_query = self._ensure_limit_clause(sql_query, max_results)
            
            # Configure job
            job_config = bigquery.QueryJobConfig(
                dry_run=False,
                use_query_cache=True,
                maximum_bytes_billed=self.max_bytes_threshold,
                job_timeout_ms=self.max_execution_time * 1000
            )
            
            # Execute query
            start_time = datetime.now()
            query_job = self.client.query(limited_query, job_config=job_config)
            
            # Get results
            results = []
            rows_returned = 0
            
            try:
                for row in query_job:
                    results.append(dict(row))
                    rows_returned += 1
                    if rows_returned >= max_results:
                        break
            except Exception as e:
                logger.warning(f"Error retrieving results: {e}")
            
            execution_time = (datetime.now() - start_time).total_seconds()
            
            # Calculate costs
            bytes_processed = query_job.total_bytes_processed or 0
            cost_estimate = self._calculate_cost(bytes_processed)
            
            result = QueryExecutionResult(
                success=True,
                query_job_id=query_job.job_id,
                rows_returned=rows_returned,
                bytes_processed=bytes_processed,
                execution_time=execution_time,
                cost_estimate=cost_estimate,
                results=results,
                error_message=None,
                metadata={
                    'state': query_job.state,
                    'created': query_job.created.isoformat() if query_job.created else None,
                    'ended': query_job.ended.isoformat() if query_job.ended else None,
                    'cache_hit': query_job.cache_hit,
                    'total_bytes_billed': query_job.total_bytes_billed
                }
            )
            
            logger.info(f"Query executed successfully: {rows_returned} rows, {execution_time:.2f}s")
            return result
            
        except Exception as e:
            logger.error(f"Query execution failed: {str(e)}")
            return QueryExecutionResult(
                success=False,
                query_job_id="",
                rows_returned=0,
                bytes_processed=0,
                execution_time=0.0,
                cost_estimate=0.0,
                results=None,
                error_message=str(e),
                metadata={'error': str(e)}
            )
    
    def _validate_security(self, sql_query: str, parsed: sql.Statement) -> Dict[str, List[str]]:
        """Validate query for security issues."""
        warnings = []
        errors = []
        
        # Check for dangerous keywords
        sql_upper = sql_query.upper()
        for keyword in self.dangerous_keywords:
            if re.search(rf'\b{keyword}\b', sql_upper):
                errors.append(f"Dangerous keyword detected: {keyword}")
        
        # Check for warning keywords
        for keyword in self.warning_keywords:
            if re.search(rf'\b{keyword}\b', sql_upper):
                warnings.append(f"Potentially expensive operation: {keyword}")
        
        # Check for SQL injection patterns
        injection_patterns = [
            r"'.*OR.*'.*'",  # OR injection
            r"'.*AND.*'.*'", # AND injection
            r"--",           # Comment injection
            r"/\*.*\*/",     # Block comment injection
        ]
        
        for pattern in injection_patterns:
            if re.search(pattern, sql_query, re.IGNORECASE):
                warnings.append(f"Potential SQL injection pattern detected")
        
        return {'warnings': warnings, 'errors': errors}
    
    def _validate_performance(self, sql_query: str, parsed: sql.Statement) -> Dict[str, List[str]]:
        """Validate query for performance issues."""
        warnings = []
        recommendations = []
        
        sql_upper = sql_query.upper()
        
        # Check for expensive patterns
        for pattern in self.expensive_patterns:
            if re.search(pattern, sql_query, re.IGNORECASE):
                warnings.append("Query contains potentially expensive operations")
                recommendations.append("Consider optimizing expensive operations")
        
        # Check for SELECT *
        if re.search(r'\bSELECT\s+\*\b', sql_upper):
            warnings.append("SELECT * can be inefficient for large tables")
            recommendations.append("Specify only needed columns instead of SELECT *")
        
        # Check for missing LIMIT
        if not re.search(self.required_patterns['limit_clause'], sql_upper):
            warnings.append("Query lacks LIMIT clause")
            recommendations.append("Add LIMIT clause to prevent large result sets")
        
        # Check for missing WHERE clause on large operations
        if 'FROM' in sql_upper and not re.search(r'\bWHERE\b', sql_upper):
            warnings.append("Query without WHERE clause may scan entire table")
            recommendations.append("Consider adding WHERE clause to filter data")
        
        # Check for CROSS JOIN
        if re.search(r'\bCROSS\s+JOIN\b', sql_upper):
            warnings.append("CROSS JOIN can produce very large result sets")
            recommendations.append("Ensure CROSS JOIN is intentional and necessary")
        
        return {'warnings': warnings, 'recommendations': recommendations}
    
    def _perform_dry_run(self, sql_query: str) -> Dict[str, Any]:
        """Perform BigQuery dry run to estimate costs and validate syntax."""
        try:
            job_config = bigquery.QueryJobConfig(dry_run=True, use_query_cache=False)
            query_job = self.client.query(sql_query, job_config=job_config)
            
            bytes_processed = query_job.total_bytes_processed
            estimated_cost = self._calculate_cost(bytes_processed)
            
            # Rough runtime estimation based on bytes processed
            estimated_runtime = min(max(bytes_processed / (1024**3) * 10, 1), 300)  # 10s per GB, 1s min, 5min max
            
            return {
                'valid': True,
                'bytes_processed': bytes_processed,
                'estimated_cost': estimated_cost,
                'estimated_runtime': estimated_runtime
            }
            
        except Exception as e:
            logger.error(f"Dry run failed: {str(e)}")
            return {
                'valid': False,
                'error': str(e),
                'bytes_processed': None,
                'estimated_cost': None,
                'estimated_runtime': None
            }
    
    def _calculate_risk_level(
        self, 
        security_result: Dict[str, List[str]], 
        performance_result: Dict[str, List[str]], 
        dry_run_result: Dict[str, Any]
    ) -> QueryRiskLevel:
        """Calculate overall risk level for query."""
        
        # Critical risk conditions
        if security_result.get('errors'):
            return QueryRiskLevel.CRITICAL
        
        if not dry_run_result.get('valid', False):
            return QueryRiskLevel.CRITICAL
        
        estimated_cost = dry_run_result.get('estimated_cost', 0)
        if estimated_cost and estimated_cost > self.max_cost_threshold:
            return QueryRiskLevel.CRITICAL
        
        bytes_processed = dry_run_result.get('bytes_processed', 0)
        if bytes_processed and bytes_processed > self.max_bytes_threshold:
            return QueryRiskLevel.CRITICAL
        
        # High risk conditions
        warning_count = len(security_result.get('warnings', [])) + len(performance_result.get('warnings', []))
        if warning_count >= 3:
            return QueryRiskLevel.HIGH
        
        if estimated_cost and estimated_cost > self.max_cost_threshold * 0.5:
            return QueryRiskLevel.HIGH
        
        # Medium risk conditions
        if warning_count >= 1:
            return QueryRiskLevel.MEDIUM
        
        if estimated_cost and estimated_cost > self.max_cost_threshold * 0.1:
            return QueryRiskLevel.MEDIUM
        
        return QueryRiskLevel.LOW
    
    def _ensure_limit_clause(self, sql_query: str, max_results: int) -> str:
        """Add LIMIT clause if not present."""
        sql_upper = sql_query.upper()
        
        if not re.search(r'\bLIMIT\s+\d+\b', sql_upper):
            # Add LIMIT clause
            sql_query = sql_query.rstrip(';')  # Remove trailing semicolon
            sql_query += f" LIMIT {max_results}"
        
        return sql_query
    
    def _calculate_cost(self, bytes_processed: int) -> float:
        """Calculate estimated cost based on bytes processed."""
        if not bytes_processed:
            return 0.0
        
        # Convert bytes to TB and calculate cost
        tb_processed = bytes_processed / (1024**4)
        return tb_processed * self.bigquery_pricing['on_demand']
    
    def analyze_query_patterns(self, queries: List[str]) -> Dict[str, Any]:
        """Analyze patterns in multiple queries for insights.
        
        Args:
            queries: List of SQL queries to analyze
            
        Returns:
            Analysis results with patterns and recommendations
        """
        try:
            analysis = {
                'total_queries': len(queries),
                'common_patterns': {},
                'security_issues': [],
                'performance_issues': [],
                'recommendations': []
            }
            
            for query in queries:
                validation = self.validate_query(query)
                
                # Collect security issues
                analysis['security_issues'].extend(validation.errors)
                
                # Collect performance issues
                analysis['performance_issues'].extend(validation.warnings)
            
            # Generate recommendations based on patterns
            if analysis['security_issues']:
                analysis['recommendations'].append(
                    "Multiple queries have security issues - review SQL generation logic"
                )
            
            if analysis['performance_issues']:
                analysis['recommendations'].append(
                    "Consider adding performance optimization rules to query generation"
                )
            
            return analysis
            
        except Exception as e:
            logger.error(f"Query pattern analysis failed: {str(e)}")
            return {'error': str(e)}
    
    def get_query_statistics(self, days: int = 7) -> Dict[str, Any]:
        """Get query statistics from BigQuery job history.
        
        Args:
            days: Number of days to look back
            
        Returns:
            Query statistics and insights
        """
        try:
            # Query BigQuery INFORMATION_SCHEMA for job statistics
            lookback_date = (datetime.now() - timedelta(days=days)).strftime('%Y-%m-%d')
            
            stats_query = f"""
            SELECT 
                COUNT(*) as total_jobs,
                AVG(total_bytes_processed) as avg_bytes_processed,
                MAX(total_bytes_processed) as max_bytes_processed,
                AVG(total_slot_ms) / 1000 as avg_slot_seconds,
                COUNT(CASE WHEN state = 'DONE' THEN 1 END) as successful_jobs,
                COUNT(CASE WHEN error_result IS NOT NULL THEN 1 END) as failed_jobs
            FROM `{self.project_id}`.`region-{self.location.lower()}`.INFORMATION_SCHEMA.JOBS_BY_PROJECT
            WHERE creation_time >= '{lookback_date}'
            AND job_type = 'QUERY'
            """
            
            query_job = self.client.query(stats_query)
            results = list(query_job)
            
            if results:
                row = results[0]
                return {
                    'period_days': days,
                    'total_jobs': row.total_jobs,
                    'successful_jobs': row.successful_jobs,
                    'failed_jobs': row.failed_jobs,
                    'success_rate': row.successful_jobs / row.total_jobs if row.total_jobs > 0 else 0,
                    'avg_bytes_processed': row.avg_bytes_processed,
                    'max_bytes_processed': row.max_bytes_processed,
                    'avg_slot_seconds': row.avg_slot_seconds
                }
            else:
                return {'error': 'No query statistics available'}
            
        except Exception as e:
            logger.error(f"Failed to get query statistics: {str(e)}")
            return {'error': str(e)}


# Example usage and testing
if __name__ == "__main__":
    # Example configuration
    PROJECT_ID = "your-project-id"
    
    # Initialize service
    service = BigQueryValidationService(PROJECT_ID)
    
    # Example queries for testing
    test_queries = [
        "SELECT name, email FROM customers ORDER BY created_date DESC LIMIT 10",  # Safe
        "SELECT * FROM orders WHERE amount > 1000",  # Missing LIMIT
        "DELETE FROM customers WHERE status = 'inactive'",  # Dangerous
        "SELECT c.name, SUM(o.amount) FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.name"  # Missing LIMIT
    ]
    
    for i, query in enumerate(test_queries):
        print(f"\n--- Query {i+1} ---")
        print(f"SQL: {query}")
        
        try:
            # Validate query
            result = service.validate_query(query)
            print(f"Status: {result.status.value}")
            print(f"Risk: {result.risk_level.value}")
            print(f"Safe: {result.is_safe}")
            
            if result.warnings:
                print(f"Warnings: {result.warnings}")
            if result.errors:
                print(f"Errors: {result.errors}")
            if result.recommendations:
                print(f"Recommendations: {result.recommendations}")
            
            # Execute if safe
            if result.is_safe:
                exec_result = service.execute_query_safely(query, result)
                print(f"Execution: {'Success' if exec_result.success else 'Failed'}")
                if exec_result.error_message:
                    print(f"Error: {exec_result.error_message}")
                    
        except Exception as e:
            print(f"Error: {e}")